// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2sUQvM37NXEtk2OxKxu_joOcPzGx9EEY',
    appId: '1:478613057941:web:6c195d042cac458baf469c',
    messagingSenderId: '478613057941',
    projectId: 'noteapp-2e158',
    authDomain: 'noteapp-2e158.firebaseapp.com',
    storageBucket: 'noteapp-2e158.firebasestorage.app',
    measurementId: 'G-61MNDM1HND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtaPVl6bCTdcLls-xJOtKrwpX95pfwDDA',
    appId: '1:478613057941:android:c3269c0935e1cb94af469c',
    messagingSenderId: '478613057941',
    projectId: 'noteapp-2e158',
    storageBucket: 'noteapp-2e158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-7oIvXBirU-Ugua_9cmZqxaCsPkCu-cc',
    appId: '1:478613057941:ios:060fbbad450cf11baf469c',
    messagingSenderId: '478613057941',
    projectId: 'noteapp-2e158',
    storageBucket: 'noteapp-2e158.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-7oIvXBirU-Ugua_9cmZqxaCsPkCu-cc',
    appId: '1:478613057941:ios:060fbbad450cf11baf469c',
    messagingSenderId: '478613057941',
    projectId: 'noteapp-2e158',
    storageBucket: 'noteapp-2e158.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2sUQvM37NXEtk2OxKxu_joOcPzGx9EEY',
    appId: '1:478613057941:web:28e2ec9fdaa491c3af469c',
    messagingSenderId: '478613057941',
    projectId: 'noteapp-2e158',
    authDomain: 'noteapp-2e158.firebaseapp.com',
    storageBucket: 'noteapp-2e158.firebasestorage.app',
    measurementId: 'G-NF0FZ57MPX',
  );
}
